{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ml-platform-ingress
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.paths.mlService }}
            pathType: Prefix
            backend:
              service:
                name: ml-service
                port:
                  number: {{ .Values.mlService.service.port }}
          - path: {{ .Values.ingress.paths.prometheus }}
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: {{ .Values.prometheus.service.port }}
          - path: {{ .Values.ingress.paths.grafana }}
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: {{ .Values.grafana.service.port }}
{{- end }}
