apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.service.port }}
      targetPort: 5432
  type: {{ .Values.postgres.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: ml-service
spec:
  selector:
    app: ml-service
  ports:
    - protocol: TCP
      port: {{ .Values.mlService.service.port }}
      targetPort: 8000
      nodePort: {{ .Values.mlService.service.nodePort }}
  type: {{ .Values.mlService.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: {{ .Values.prometheus.service.port }}
      targetPort: 9090
      nodePort: {{ .Values.prometheus.service.nodePort }}
  type: {{ .Values.prometheus.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: {{ .Values.grafana.service.port }}
      targetPort: 3000
      nodePort: {{ .Values.grafana.service.nodePort }}
  type: {{ .Values.grafana.service.type }}
